---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-arg
spec:
  containers:
    - name: myapp
      image: nginx
      args:
        -  -port = 8088
      ports:
        - containerPort: 8080
          protocol: TCP
