---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-cm
spec:
  containers:
    - name: myapp
      image: ghcr.io/nobreak-labs/go-myweb:alpine
      env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: myapp-cm-message
              key: message
      ports:
        - containerPort: 8080
          protocol: TCP
