# spec.concurrencyPolicy: Allow (기본값)
# 잡 동시 실행이 가능하기 때문에 startingDeadlineSeconds의 실행을 확인할 수는 없는 크론잡이다.
# startingDeadlineSeconds: 100은 이미 잡이 실행 중이어서 실행되지 못한 잡의 실행을 100초까지 유예하겠다는 뜻.
# 100초 동안 이전 잡이 완료되지 않는다면 버리고, 완료된다면 대기 중이었던 잡을 실행
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mypap-cj-dl-al
spec:
  schedule: "* * * * *"
  startingDeadlineSeconds: 100
  jobTemplate:
    spec: 
      template:
        metadata:
          labels:
            app: myapp-cj-dl-al
        spec:
          restartPolicy: OnFailure
          containers:
            - name: sleep
              image: busybox
              command: ["sleep", "70"]
