# 다중 포트는 각 포트마다 이름을 지어줘야 한다.
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc-multiport
spec:
  type: ClusterIP
  selector:
    app: myapp-rs
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
