apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs-git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-rs-git
  template:
    metadata:
      labels:
        app: myapp-rs-git
    spec:
      initContainers:
        - name: git-clone
          image: alpine/git
          args:
            - clone
            - https://github.com/c1t1d0s7/startbootstrap-sb-admin-2.git
            - /repo
          volumeMounts:
            - name: git-repository
              mountPath: /repo
      containers:
        - name: web-server
          image: nginx:alpine
          volumeMounts:
            - name: git-repository
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: git-repository
          emptyDir: {}
