apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-rs
  template:
    metadata:
      labels:
        app: myapp-rs
    spec:
      containers:
        - name: myapp
          image: ghcr.io/nobreak-labs/go-myweb:v1.0
          ports:
            - containerPort: 8080
