# kubectl get po --show-labels
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-label
  labels:
    env: dev
    tier: frontend
spec:
  containers:
    - name: myapp
      image: ghcr.io/nobreak-labs/go-myweb:alpine
      ports:
        - containerPort: 8080
          protocol: TCP
