---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-liveness
spec:
  containers:
    - name: myapp
      image: ghcr.io/nobreak-labs/go-myweb:alpine
      ports:
        - containerPort: 8080
          protocol: TCP
      livenessProbe:
        httpHet:
          path: /health
          port: 8080
