# ExecAction 프로브 핸들러 사용
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-exec
spec:
  containers:
    - name: myapp
      image: ghcr.io/nobreak-labs/go-myweb:alpine
      ports:
        - containerPort: 8080
          protocol: TCP
      startupProbe:
        exec:
          command:
            - ls
            - /test
      livenessProbe:
        httpGet:
          path: /health?code=404
          port: 8080
